import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "../../node_modules/react-toastify/dist/ReactToastify.css";

import { Space_Grotesk } from 'next/font/google';

// Load the font with specific weights and subsets
const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'], 
  weight: ['500'], 
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
